### ISSUE TITLE
Can you translate the output log of the script into English?

### ISSUE THREAD

**Issue by sinneh** [dwydler/Powershell-Skripte#3]
fujtisu-support_check-warranty-status.ps1

**Comment by dwydler** [comment]
Hi @sinneh,
that's a good idea.

A few minutes ago I pushed a new version of the script. The default language is english. Other translations are welcome.

You can found the newest version [here](https://codeberg.org/wd/Powershell-Skripte/src/branch/master/Fujitsu/FujitsuWarrantyStatusChecker). Please try it out.


Best regards,
Daniel

**Comment by sinneh** [comment]
Thank you for your great work，test work is normal
